apiVersion: v1
kind: Service
metadata:
  labels:
    cattle.io/creator: norman
  name: garnet-fe
  namespace: garnet
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: deployment-garnet-garnet-fe
  type: NodePort
